services:
  - postgresql
addons:
  postgresql: "9.5"
language: python
cache: pip
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE jobdb;' -U postgres
script:
  - pytest .
after_success:
  - coveralls
